apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - image: docker.io/gmarcy/app-sample
          imagePullPolicy: Always
          name: sample
          ports:
            - containerPort: 9080
